# config file for processing functional count data 

# SnakeMake rules to use 
process_fastq:   
    activate: false

bowtie_idx:
    activate: false

bowtie_align:
    activate: false

process_bam:
    activate: false

count_umis:
    activate: false

# experiment details 
RAW_DATA:
    # path to input raw haircut fastqs
    "/rumi/shams/abe/Projects/sc-haircut-net/raw-data"

DATA:
    # path to output data files
    "output"

HAIRCUT_FASTA:
    "/rumi/shams/abe/Projects/sc-haircut-net/sc-haircut/data/hairpin.fa"

HAIRCUT_SAMPLES:
    - mix15_repair
    - mix30_repair
    - mix60_repair

10X_WHITELIST:
    # known barcodes used in the 10x libraires to use for error correction
    "/rumi/shams/abe/Projects/sc-haircut-net/reanalyzed-data/barnyard_mrna/10xv2_whitelist.txt"

CELL_BARCODES:
    # barcodes considered to be cells based on cellrange count run on mRNA
    # data
    - "/rumi/shams/abe/Projects/sc-haircut-net/reanalyzed-data/mix15_mrna/counts_unfiltered/cellranger/barcodes.tsv" 
    - "/rumi/shams/abe/Projects/sc-haircut-net/reanalyzed-data/mix60_mrna/counts_unfiltered/cellranger/barcodes.tsv"
    - "/rumi/shams/abe/Projects/sc-haircut-net/reanalyzed-data/mix30_mrna/counts_unfiltered/cellranger/barcodes.tsv"

SRC:
    # path to directory with source code " 
    "src"


